# Приветственные сообщения
start: "👋 Привет! Я — ваш погодный помощник для путешествий! 🌦️🧳


Что я могу сделать?

	•	Покажу прогноз погоды для маршрута вашей поездки. 🚗✈️

	•	Вы узнаете, какая будет температура, осадки и ветер в нужные даты и местах.

	•	Отображу прогноз в удобном формате: текстом, графиками или ссылками на визуализации.


Как это работает?

1️⃣ Отправьте команду /weather.

2️⃣ Укажите маршрут: начальную точку, конечную точку и остановки (если есть). 🗺️

3️⃣ Выберите временной интервал прогноза с помощью удобных кнопок. ⏰

А я покажу погоду в каждом пункте вашего маршрута! ☀️🌧️💨


Готовы? Нажмите /weather и начнём! 🚀"

help: "🆘 /help — Справка по командам бота 🆘

Я помогу вам отслеживать погоду для поездок и маршрутов. Вот список команд, которые вы можете использовать:

	•	/start — Начать работу с ботом и получить приветственное сообщение.

	•	/weather — Узнать прогноз погоды для вашей поездки. Укажите маршрут и даты."
command_error: "Команда не распознана"

# Ввод точки
choose_point:
    method: "Выберите способ, как вы хотите задать точку:"
    cords: "🌍 Ввести координаты"
    city: "🏙️ Ввести название города"
    enter_long: "🌍 Введите долготу (например, 37.6173):"
    enter_lat: "🌍 Введите широту (например, 55.7558):"
    enter_city: "🏙️ Введите название города (например, Москва):"
    confirm_message: "Проверьте введенные данные:

    Координаты: {long}, {lat}

    Город: {city}"
    error_message: "❌ Ошибка. 
    
    Проверьте введенные данные или попробуйте еще раз."
    error_message_try_again: "🟢 Ввести заново"
    error_message_cancel: "❌ Отменить"
    confirm_button: "✅ Подтвердить"
    cancel_button: "❌ Отменить"

trip_weather:
    starting_point: "✈️ Давайте определим погоду в вашем путешествии. Начнем с выбора начальной точки!"
    confirm_starting_point: "🟢 Начать"
    cancel_starting_point: "❌ Отменить"
    ending_point: "🏁 Отлично, теперь выберите конечную точку вашего маршрута."
    confirm_ending_point: "🟢 Выбрать точку"
    cancel_ending_point: "❌ Отменить"
    additional_points: "📍 Хотите добавить дополнительные точки на маршруте? Это может быть полезно, чтобы узнать погоду в промежуточных местах.


    Текущий маршрут:

    ✈️ {start_point}

    {points}
    🏁 {end_point}"
    add_point: "➕ Добавить точку"
    continue: "✅ Продолжить"
    duration: "⏳ Сколько дней продлится ваше путешествие?"
    1 day: "🕒 1 день"
    3 days: "🕒 3 дня"
    5 days: "🕔 5 дней"
    7 days: "🗓️ 7 дней"
    custom: "✏️ Ввести вручную"
    custom_duration: "⏳ Введите длительность в днях (от 1 до 7):" 
    duration_error: "❌ Некорректное значение. Введите число от 1 до 7"
    finish: "Маршрут:

    ✈️ {start_point}

    {points}
    🏁 {end_point}
    

    ⏰ Длительность в днях: {duration}
    

    Все верно?"
    finish_confirm: "✅ Подтвердить"
    finish_cancel: "❌ Отменить"
    command_error: "Команда не распознана"
    goodbye: "До свидания!"

weather_view:
    point: "Выберите точку, в которой вы хотите узнать погоду:"
    all_dates: "Весь период"
    date: "Выберите дату прогноза:"
    measure: "Выберите нужный показатель:"
    temp_min: "Минимальная температура"
    temp_max: "Максимальная температура"
    wind_speed: "Скорость ветра"
    precipitation_mm: "Осадки, мм"
    back: "Назад"
    end: "Завершить"
    goodbye: "До свидания!"
    forecast_error: "❌ При получении прогноза произошла ошибка."
    command_error: "Команда не распознана"
    plot_error: "❌ При получении графика произошла ошибка."
    plot: "🌍: {point}
    
    📏 Показатель: {measure}"